project:
  output-dir: _handouts

format:
  pdf:
    geometry:
      - top=15mm
      - bottom=20mm
    keep-md: false
    keep-tex: false
    toc: true
    fig-pos: "H"
    toc-title: Contents
    df-print: tibble
    links-as-notes: true
    documentclass: article
    colorlinks: true
    number-sections: true
    number-depth: 3

execute:
  warning: false
  message: false
  cache: false
  freeze: auto

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
