project:
  type: website
  output-dir: _site

website:
  title: "Hoff Bayesian Statistics"
  site-url: https://d-morrison.github.io/hoff-bayesian-statistics/
  description: "Lecture notes by Jesse Mu for Peter D. Hoff's 'A First Course in Bayesian Statistical Methods'"
  page-footer:
    center: "Â© Jesse Mu"
  back-to-top-navigation: true
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/d-morrison/hoff-bayesian-statistics
  repo-actions: [edit, issue, source]
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Chapters"
        menu:
          - text: "Chapter 1: Introduction and examples"
            href: 1.qmd
          - text: "Chapter 2: Belief, probability, and exchangeability"
            href: 2.qmd
          - text: "Chapter 3: One-parameter models"
            href: 3.qmd
          - text: "Chapter 4: Monte Carlo approximation"
            href: 4.qmd
          - text: "Chapter 5: The Normal Model"
            href: 5.qmd
          - text: "Chapter 6: Posterior approximation with the Gibbs sampler"
            href: 6.qmd
          - text: "Chapter 7: The multivariate normal model"
            href: 7.qmd
          - text: "Chapter 8: Group comparisons and hierarchical modeling"
            href: 8.qmd
          - text: "Chapter 9: Linear regression"
            href: 9.qmd
          - text: "Chapter 10: Nonconjugate priors and Metropolis-Hastings algorithms"
            href: 10.qmd
      - text: "Infinite Relational Model"
        href: irm.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: true
    code-tools: true
    code-link: true
    code-summary: "Show R code"
    css: styles.css
    highlight-style: pygments
    lightbox: true
    link-external-icon: true
    embed-resources: false
    fig-cap-location: top
    html-math-method: mathjax
    number-sections: true
    number-depth: 3
    df-print: paged
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (z)"
  revealjs:
    lightbox: true
    theme: dark
    embed-resources: true
    fig-cap-location: top
    html-math-method: mathjax
    smaller: true
    number-sections: true
    progress: true
    incremental: false
    df-print: paged
    number-depth: 2
    slide-number: true
    shift-heading-level-by: -1
    slide-level: 2
    scrollable: true
    echo: true
    margin: 0.0
    code-fold: true
    code-link: true
    code-summary: "[R code]"
    auto-stretch: true
    fig-height: 5
    fig-width: 7

comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true
